<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Shauzabs-MacBook-Pro.local" name="RunCucumberTest" tests="1" failures="1" timestamp="6 Jun 2020 23:00:05 GMT" time="43.763" errors="0">
  <testcase name="runScenario" time="43.763" classname="RunCucumberTest">
    <failure type="org.testng.SkipException" message="cucumber.api.PendingException: TODO: implement me
	at stepdefs.SubmitCase.successful_submission_message_is_displayed(SubmitCase.java:59)
	at ✽.Successful submission message is displayed(classpath:features/submitApplication.feature:10)
">
      <![CDATA[org.testng.SkipException: cucumber.api.PendingException: TODO: implement me
	at stepdefs.SubmitCase.successful_submission_message_is_displayed(SubmitCase.java:59)
	at ✽.Successful submission message is displayed(classpath:features/submitApplication.feature:10)

	at cucumber.api.testng.TestCaseResultListener.getError(TestCaseResultListener.java:54)
	at cucumber.api.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:62)
	at cucumber.api.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: cucumber.api.PendingException: TODO: implement me
	at stepdefs.SubmitCase.successful_submission_message_is_displayed(SubmitCase.java:59)
	at ✽.Successful submission message is displayed(classpath:features/submitApplication.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- RunCucumberTest -->
